# Generated by Django 2.0.6 on 2018-08-05 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minsta', '0004_provisionaluser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provisionaluser',
            old_name='uuid',
            new_name='register_uuid',
        ),
    ]
