# Generated by Django 2.0.6 on 2018-08-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minsta', '0005_auto_20180805_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisionaluser',
            name='posted_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
