# Generated by Django 2.0.6 on 2018-08-06 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minsta', '0006_provisionaluser_posted_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provisionaluser',
            old_name='posted_at',
            new_name='created_at',
        ),
    ]
