# Generated by Django 2.0.6 on 2018-08-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minsta', '0007_auto_20180806_0826'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgetPasswordUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_uuid', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(default=None)),
            ],
        ),
    ]
