# Generated by Django 2.0.6 on 2018-08-22 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minsta', '0008_forgetpassworduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('cafe_name', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('hp', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('work_time', models.TextField(blank=True)),
            ],
        ),
    ]
