# Generated by Django 2.0.6 on 2018-08-22 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minsta', '0009_cafe'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cafe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='minsta.Cafe'),
            preserve_default=False,
        ),
    ]
