# Generated by Django 2.1.1 on 2018-09-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minsta', '0013_auto_20180831_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvisionalRegistrationCafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(blank=True)),
                ('cafe_name', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('hp', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('work_time', models.TextField(blank=True)),
                ('area', models.TextField(blank=True)),
            ],
        ),
    ]
